---
# deploy.yml
- name: Deploy our app
  hosts: all
  become: true
  vars:
    welcome_message: "Welcome to Ansible world!"
    document_root: /var/www/html
    app_root: webapp
  tasks:
    - name: Delete existing index.html
      ansible.builtin.file:
        path: /usr/share/nginx/html/index.html
        state: absent
    - name: Create web app folder
      ansible.builtin.file:
        path: "{{ document_root }}/{{ app_root }}"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
        state: directory
    - name: Copy our index.html
      ansible.builtin.template:
        src: "files/{{ app_root }}/index.html.j2"
        dest: "{{ document_root }}/{{ app_root }}/index.html"
        owner: root
        group: root
        mode: u=rw,g=r,o=r
    - name: Apply Nginx template
      ansible.builtin.template:
        src: files/nginx.conf.j2
        dest: /etc/nginx/sites-available/default
        owner: root
        group: root
        mode: u=rw,g=r,o=r
      notify: Restart Nginx
    - name: Enable new site
      ansible.builtin.file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
      notify: Restart Nginx
    - name: Allow all access to tcp port 80
      ufw:
        rule: allow
        port: '80'
        proto: tcp

  handlers:
    - name: Restart Nginx
      ansible.builtin.service:
        name: nginx
        state: restarted
