name: Deploy via Ansible
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: run playbook
      run: |
        ansible-playbook --version
