name: Deploy via Ansible
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: run playbook
      run: |
        ansible-playbook --version
